### ISSUE TITLE
RGB scaleSpeed Berechnungsfehler

### ISSUE THREAD

**Issue by gbrehmer** [LechnerRobert/UDPtoDMX#1]
https://github.com/LechnerRobert/UDPtoDMX/blob/3f364ee4ad739c619898e88dced6290030664349/src/main.cpp#L40-L53

Kann es sein, dass hier etwas am Algorithmus nicht passt?
Beispiel: 160 speed (60 x 147ms), 20 dx, 80 dmax

Da kommt dann wenn ich mich nicht verrechnet hab 154 als return Wert heraus. Jedoch müsste für 20 dx zu 80 dmax der Wert ja 4x skaliert werden und das würde dann nicht in den 100er Block passen und man müsste es in den 0er Block umrechnen. Der Wert müsste 240 x 147ms nahe kommen, und nach der vorhandenen Skala gibt es dann nur 240 / 4 * 591ms, also 60 als Ziel Returnwert?!

**Comment by LechnerRobert** [comment]
ja da ist ein Fehler 
...(sp = 255)) 
ist natülich falsch

hab ich korrigiert
das Ergebnis dann aber "korrekt" (199)

kannst du hier testen

https://onlinegdb.com/Sy6x2RDG4

umrechnen auf "0er Block" wäre möglich,

**Comment by gbrehmer** [comment]
ahja sorry, sp wird da ja verglichen, hatte mit ret < 200 gerechnet
